---
title: "Data Memo"
subtitle: |
  | Final Project 
  | Data Visualization (STAT 302)
author: "Arturo Fonseca"
pagetitle: "Data Memo Arturo Fonseca"
date: today

format:
  html:
    toc: true
    toc-location: left
    embed-resources: true
    link-external-newwindow: true
    fig-dpi: 300

execute:
  warning: false

from: markdown+emoji 
reference-location: margin
citation-location: margin
---

## Instructions

After selecting data for the final project write up a short memo that at minimum covers the following:

### Data source

Identify and describe your data source or sources --- citations would be appropriate. Citations will typically include links to the data source.

:::callout-tip
## Solution

This data source is from the CDC and includes over 250K individuals. This dataset specifically is from 2014 (for no specific reason other than it was the one referenced in a Kaggle dataset). It includes 23 columns, 1 of which is an indicator variable describing whether an individual has diabetes.
<https://www.cdc.gov/brfss/annual_data/annual_2014.html/>

:::

### Why this data

The reason for your choice of data. Is it interesting to you? Challenging? Is this part of a larger research project? State any questions of interest that might be motivating your choice of data. Include any other motivations or background that you believe to be relevant.

In general, we are asking you to tell us what sorts of questions you are trying to answer or what story you are trying to convey. Maybe you are just exploring a topic that is interesting to you and you are prospecting for a story to tell and that is okay too.

:::callout-tip
# Solution

I wanted to use this dataset because I thought it could be very valuable to draw insights into people that have diabetes vs. people that don't. For example, is there a relationship between smoking and having diabetes?

I also chose it because it is very large (too large in fact), meaning there is a plenty to look at. This also means that this dataset is useful and descriptive, since it is used in a lot of research papers. It could also be a bit of a challenge to wrangle this data to get it to a size that is workable for `ggplot2`.

:::

### Visualization plan

Share your plan for visualizing the data. Are you going with a presentation and static graphics, presentation with a mix animated and static graphics, or will you attempt to build an app/dashboard? 

This is just an initial plan and you don't have to stick to it.

:::callout-tip
## Solution

I'm kind of motivated to do either a Shiny app or a Quarto presentation. I think a Shiny app would be best because viewers could pick what variables they want to view to see if there is a relationship with diabetes.

:::

### Initial data issues

Have you been able to download the data and read it into R? If not, where are you getting stuck?

Have you been able to examine the data a little? If yes, have you spotted any potential issues like difficult data wrangling or data quality issues such as a significant amount of missing data?

:::callout-tip
## Solution

Luckily, there is no missingness. My only issues (2) is that there is a clear class imbalance: there is an overwhelming number of people who don't have diabetes as compared to people that do. This isn't a machine learning task, but it would still be a challange to equally represent both groups. Another is issue is the size of the dataset. 250K+ observations is obviously way too much to plot, so I would need a systematic way to select data points to plot.

:::

### Misc

Students are encourage to add any other information that they think would be useful to communicate about their data and their plan.

If are seeking permission to work with a partner or partners then you should indicate it at the top of this memo (add a new section). Should include how you plan to work together or why working together makes sense for the project.

:::callout-tip
## Solution?

I wonder if I should choose a more recent year or if it doesn't really matter.

:::
